### ISSUE TITLE
./dnsupdate.sh: line 34: [: too many arguments

### ISSUE THREAD

**Issue by microfx** [rabe0577/inwx-dyndns-update#1]
Hey! 

I am getting: 
./dnsupdate.sh: line 34: [: too many arguments

Any idea what's going on? 

Cheers!

**Comment by rabe0577** [comment]
Hey,

you must run it with the bash interpreter. 
Otherwise you will always get these errors.

Cheers!

**Comment by microfx** [comment]
Hey! 

What is a bash interpreter?

**Comment by rabe0577** [comment]
Run it with:
`bash dnsupdate.sh`
instead of ./

**Comment by microfx** [comment]
Aight! Maybe add that to the docs :) Seems to be working - thanks!
